<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>GAIP</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/GAIP.ico</ApplicationIcon>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/gaip-logo.png;Assets/GAIP.ico" />
    <ProjectReference Include="../GAIP.Sync/GAIP.Sync.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="Avalonia.Wayland" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64' Or '$(RuntimeIdentifier)' == 'linux-arm64'">
    <Content Include="Linux/*" Link="%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Assets/icons/**/*.png" Link="icons/%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
